import { isDefaultTitle } from "@/lib/title-utils";
import { conversationService } from "./conversation.service";

/**
 * Manages active polling timers for asynchronous title generation updates.
 */
class ConversationPollingService {
  private activeTimers = new Map<string, NodeJS.Timeout>();

  /**
   * Starts polling for an updated title generated by backend background workflows.
   */
  startTitlePolling(
    convId: string,
    initialTitle: string,
    onTitleUpdated: (newTitle: string) => void
  ): void {
    this.stopTitlePolling(convId);

    let attempts = 0;
    const maxAttempts = 10;
    const pollIntervalMs = 1500;

    const timer = setInterval(async () => {
      attempts += 1;

      if (attempts > maxAttempts) {
        this.stopTitlePolling(convId);
        return;
      }

      try {
        const title = await conversationService.fetchConversationTitle(convId);
        const serverTitle = title?.trim();

        if (serverTitle && serverTitle !== initialTitle && !isDefaultTitle(serverTitle)) {
          onTitleUpdated(serverTitle);
          this.stopTitlePolling(convId);
        }
      } catch (err) {
        console.warn(`Failed to poll conversation title for ${convId}:`, err);
      }
    }, pollIntervalMs);

    this.activeTimers.set(convId, timer);
  }

  /**
   * Cancels any active title poll timer for a specific conversation.
   */
  stopTitlePolling(convId: string): void {
    const existingTimer = this.activeTimers.get(convId);
    if (existingTimer) {
      clearInterval(existingTimer);
      this.activeTimers.delete(convId);
    }
  }

  /**
   * Cancels all active title poll timers.
   */
  clearAllTitlePolling(): void {
    this.activeTimers.forEach((timer) => clearInterval(timer));
    this.activeTimers.clear();
  }
}

export const conversationPollingService = new ConversationPollingService();
